### ISSUE TITLE
Remove "bluebird" dependency

### ISSUE THREAD

**Issue by gkcgautam** [ezekg/download-in-browser#3]
Please remove the bluebird dependency as the build pipeline might already include a polyfill for Promise support in browser.
The size of this package is [huge](https://bundlephobia.com/result?p=download-in-browser@0.1.5) right now due to this.

**Comment by ezekg** [comment]
Thanks! You’re right. Can you submit a PR? Would be happy to merge.

**Comment by gkcgautam** [comment]
Pull request: #4

**Comment by ezekg** [comment]
Closed in #4. Published v0.2 to npm. 👍
